spring.application.name=jobmatch

spring.datasource.url=jdbc:postgresql://localhost:5432/job_match_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver